spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${S2_DB_HOST:localhost}:${S2_DB_PORT:15432}/${S2_DB_DATABASE:postgres}?stringtype=unspecified
    username: ${S2_DB_USER:postgres}
    password: ${S2_DB_PASSWORD:postgres}
  sql:
    init:
      continue-on-error: true
      mode: never
      username: ${S2_DB_USER:postgres}
      password: ${S2_DB_PASSWORD:postgres}
      schema-locations: classpath:db/schema-postgres-common.sql,classpath:db/schema-postgres.sql,classpath:db/schema-postgres-demo.sql
      data-locations: classpath:db/data-postgres-common.sql,classpath:db/data-postgres.sql,classpath:db/data-postgres-demo.sql
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: ${FLYWAY_BASELINE_VERSION:-1}
    locations: classpath:db/migration/postgresql
    table: flyway_schema_history
    out-of-order: false
    validate-on-migrate: true
  quartz:
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      org.quartz.jobStore.tablePrefix: QRTZ_
      org.quartz.jobStore.selectWithLockSQL: "SELECT * FROM {0}LOCKS WHERE SCHED_NAME = {1} AND LOCK_NAME = ? FOR UPDATE"
