server:
  servlet:
    context-path:
  port: 9081

spring:
  profiles:
    active: ${S2_DB_TYPE:h2}
  application:
    name: headless
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

authentication:
  enable: true
  exclude:
    path: /api/auth/user/register,/api/auth/user/login
  token:
    http:
      header:
        key: Authorization
