spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${S2_DB_HOST:localhost}:${S2_DB_PORT:3306}/${S2_DB_DATABASE:mysql}?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: ${S2_DB_USER:root}
    password: ${S2_DB_PASSWORD:}
  sql:
    init:
      continue-on-error: true
      mode: never
      username: ${S2_DB_USER:root}
      password: ${S2_DB_PASSWORD:}
      schema-locations: classpath:db/schema-mysql-common.sql,classpath:db/schema-mysql.sql,classpath:db/schema-mysql-demo.sql
      data-locations: classpath:db/data-mysql-common.sql,classpath:db/data-mysql.sql,classpath:db/data-mysql-demo.sql
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: ${FLYWAY_BASELINE_VERSION:-1}
    locations: classpath:db/migration/mysql
    table: flyway_schema_history
    out-of-order: false
    validate-on-migrate: false
  quartz:
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      org.quartz.jobStore.tablePrefix: QRTZ_
      org.quartz.jobStore.selectWithLockSQL: "SELECT * FROM {0}LOCKS WHERE SCHED_NAME = {1} AND LOCK_NAME = ? FOR UPDATE"
