CREATE TABLE `s2_query_stat_info` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `trace_id` varchar(200) DEFAULT NULL COMMENT '查询标识',
  `domain_id` bigint(20) DEFAULT NULL COMMENT '主题域ID',
  `user`    varchar(200) DEFAULT NULL COMMENT '执行sql的用户',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `query_type` varchar(200) DEFAULT NULL COMMENT '查询对应的场景',
  `query_type_back` int(10) DEFAULT '0' COMMENT '查询类型, 0-正常查询, 1-预刷类型',
  `query_sql_cmd` mediumtext COMMENT '对应查询的struct',
  `sql_cmd_md5` varchar(200) DEFAULT NULL COMMENT 'sql md5值',
  `query_struct_cmd` mediumtext COMMENT '对应查询的struct',
  `struct_cmd_md5` varchar(200) DEFAULT NULL COMMENT 'sql md5值',
  `sql` mediumtext COMMENT '对应查询的sql',
  `sql_md5` varchar(200) DEFAULT NULL COMMENT 'sql md5值',
  `query_engine` varchar(20) DEFAULT NULL COMMENT '查询引擎',
  `elapsed_ms` bigint(10) DEFAULT NULL COMMENT '查询耗时',
  `query_state` varchar(20) DEFAULT NULL COMMENT '查询最终状态',
  `native_query` int(10) DEFAULT NULL COMMENT '1-明细查询,0-聚合查询',
  `start_date` varchar(50) DEFAULT NULL COMMENT 'sql开始日期',
  `end_date` varchar(50) DEFAULT NULL COMMENT 'sql结束日期',
  `dimensions` mediumtext COMMENT 'sql 涉及的维度',
  `metrics` mediumtext COMMENT 'sql 涉及的指标',
  `select_cols` mediumtext COMMENT 'sql select部分涉及的标签',
  `agg_cols` mediumtext COMMENT 'sql agg部分涉及的标签',
  `filter_cols` mediumtext COMMENT 'sql where部分涉及的标签',
  `group_by_cols` mediumtext COMMENT 'sql grouy by部分涉及的标签',
  `order_by_cols` mediumtext COMMENT 'sql order by部分涉及的标签',
  `use_result_cache` tinyint(1) DEFAULT '-1' COMMENT '是否命中sql缓存',
  `use_sql_cache` tinyint(1) DEFAULT '-1' COMMENT '是否命中sql缓存',
  `sql_cache_key` mediumtext COMMENT '缓存的key',
  `result_cache_key` mediumtext COMMENT '缓存的key',
  PRIMARY KEY (`id`),
  KEY `domain_index` (`domain_id`)
) COMMENT='查询统计信息表'
