export const DND_RENDER_ID = 'DND_NDOE';
export const GROUP_NODE_RENDER_ID = 'GROUP_NODE_RENDER_ID';
export const DATASOURCE_NODE_RENDER_ID = 'DATASOURCE_NODE';
export const NODE_WIDTH = 180;
export const NODE_HEIGHT = 72;
