-- V23: Alert subscription tables (alert rules, executions, events)

CREATE TABLE IF NOT EXISTS `s2_alert_rule` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(200) NOT NULL,
    `description` VARCHAR(500) DEFAULT NULL,
    `dataset_id` BIGINT NOT NULL,
    `query_config` TEXT NOT NULL,
    `conditions` TEXT NOT NULL,
    `cron_expression` VARCHAR(100) NOT NULL,
    `enabled` TINYINT DEFAULT 1,
    `owner_id` BIGINT DEFAULT NULL,
    `delivery_config_ids` VARCHAR(500) DEFAULT NULL,
    `silence_minutes` INT DEFAULT 60,
    `max_consecutive_failures` INT DEFAULT 5,
    `consecutive_failures` INT DEFAULT 0,
    `disabled_reason` VARCHAR(1000) DEFAULT NULL,
    `retry_count` INT DEFAULT 2,
    `retry_interval` INT DEFAULT 30,
    `quartz_job_key` VARCHAR(200) DEFAULT NULL,
    `last_check_time` DATETIME DEFAULT NULL,
    `next_check_time` DATETIME DEFAULT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `created_by` VARCHAR(100) DEFAULT NULL,
    `tenant_id` BIGINT NOT NULL DEFAULT 1,
    PRIMARY KEY (`id`),
    KEY `idx_alert_rule_tenant` (`tenant_id`),
    KEY `idx_alert_rule_dataset` (`dataset_id`),
    KEY `idx_alert_rule_enabled` (`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='告警规则表';

CREATE TABLE IF NOT EXISTS `s2_alert_execution` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `rule_id` BIGINT NOT NULL,
    `status` VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    `start_time` DATETIME DEFAULT NULL,
    `end_time` DATETIME DEFAULT NULL,
    `total_rows` BIGINT DEFAULT 0,
    `alerted_rows` BIGINT DEFAULT 0,
    `silenced_rows` BIGINT DEFAULT 0,
    `error_message` VARCHAR(2000) DEFAULT NULL,
    `execution_time_ms` BIGINT DEFAULT NULL,
    `tenant_id` BIGINT NOT NULL DEFAULT 1,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_alert_execution_rule` (`rule_id`),
    KEY `idx_alert_execution_status` (`status`),
    KEY `idx_alert_execution_tenant` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='告警执行记录表';

CREATE TABLE IF NOT EXISTS `s2_alert_event` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `execution_id` BIGINT NOT NULL,
    `rule_id` BIGINT NOT NULL,
    `condition_index` INT NOT NULL,
    `severity` VARCHAR(20) NOT NULL DEFAULT 'WARNING',
    `alert_key` VARCHAR(300) NOT NULL,
    `dimension_value` VARCHAR(500) DEFAULT NULL,
    `metric_value` DOUBLE DEFAULT NULL,
    `baseline_value` DOUBLE DEFAULT NULL,
    `deviation_pct` DOUBLE DEFAULT NULL,
    `message` TEXT DEFAULT NULL,
    `delivery_status` VARCHAR(20) DEFAULT 'PENDING',
    `silence_until` DATETIME DEFAULT NULL,
    `tenant_id` BIGINT NOT NULL DEFAULT 1,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_alert_event_execution` (`execution_id`),
    KEY `idx_alert_event_alert_key` (`alert_key`),
    KEY `idx_alert_event_severity` (`severity`),
    KEY `idx_alert_event_rule` (`rule_id`),
    KEY `idx_alert_event_silence` (`silence_until`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='告警事件表';
