package com.tencent.supersonic.headless.api.pojo;

import lombok.Data;

@Data
public class SqlInfo {

    // S2SQL generated by semantic parsers
    private String parsedS2SQL;

    // S2SQL corrected by semantic correctors
    private String correctedS2SQL;

    // SQL to be executed finally
    private String querySQL;
}
