package com.tencent.supersonic.headless.api.pojo;

import lombok.Data;

import java.io.Serializable;

@Data
public class SqlInfo implements Serializable {
    private static final long serialVersionUID = 1L;

    // S2SQL generated by semantic parsers
    private String parsedS2SQL;

    // S2SQL corrected by semantic correctors
    private String correctedS2SQL;

    // SQL to be executed finally
    private String querySQL;
}
